package klev.db.wishes

import kotlinx.serialization.Serializable

@Serializable
data class Wish(
    val id: Int = 0, // Autogenerated by database
    val userId: Int,
    val occasion: Occasion,
    val status: Status = Status.OPEN,
    val url: String?,
    val description: String?,
)
